admin:
  passphrase: "Admit"
privacy:
  hide_guidance_for_non_admin: true
guidance:
  root_path: "guidance"
  index_file: "guidance_index.csv"
taxonomy:
  groups:
    - TDEE 4000
    - TDEE 5000
    - TDEE 8000
    - TDEE 9000
    - Tech Notes (TN)
    - RAN
    - Broadcast
    - RDA
