admin:
  passphrase: "Admit"
privacy:
  hide_guidance_for_non_admin: true
guidance:
  root_path: "guidance"
  index_file: "guidance_index.csv"
ui:
  projects: ["RAN","Power Resilience","Upgrade","Other"]
  site_types: ["Greenfield","Rooftop","Streetworks","Upgrade","Swap"]
  vendors: ["Ericsson","Nokia","Huawei","ZTE","Other"]
  cabinet_locations: ["Indoor","Outdoor","Hut","Other"]
  radio_locations: ["Low Level","Midway","High Level","Unique Coverage"]
  clients: ["BTEE","VF","O2","3UK","Other"]
  suppliers: ["CEG","KTL","BT","Other"]
  mimo_options: ["1x1","2x2","4x4","8x8","Custom"]
logic:
  hide_mimo_if_project_equals: "Power Resilience"
  mimo_sectors: ["S1","S2","S3","S4"]
