# Seker-V2 configuration
entry_password: Seker123
suppliers:
  - Cellnex
  - KTL
  - Obelisk
  - Telent
  - Waldon
  - WFS
  - Syscomm
  - MJ Quinn
  - MNO Projects
  - Wireless Infrastructure Group
  - Waldon Telecom
