rules:
  - title: Example power note
    reason: "IMPORTANT NOTE: Eltek PSU must be configured as per TDEE43001 section 3.8.1"
    severity: major
    when:
      client: BTEE
      project: Power Resilience
      site_type: [Rooftop, Greenfield, Streetworks]
    must_contain:
      - "Eltek"
      - "TDEE43001"
      - "3.8.1"
